// User Roles
export enum UserRole {
  ADMIN = 'ADMIN',
  MANAGER = 'MANAGER',
  SALES_REP = 'SALES_REP'
}

// Contact Lifecycle Stages
export enum LifecycleStage {
  LEAD = 'LEAD',
  PROSPECT = 'PROSPECT',
  QUALIFIED = 'QUALIFIED',
  CUSTOMER = 'CUSTOMER',
  LOST = 'LOST'
}

// Contact Lead Status
export enum LeadStatus {
  NEW = 'NEW',
  CONTACTED = 'CONTACTED',
  INTERESTED = 'INTERESTED',
  CALLBACK_SCHEDULED = 'CALLBACK_SCHEDULED',
  DEMO_SCHEDULED = 'DEMO_SCHEDULED',
  MEETING_SCHEDULED = 'MEETING_SCHEDULED',
  PROPOSAL_SENT = 'PROPOSAL_SENT',
  NEGOTIATION = 'NEGOTIATION',
  WON = 'WON',
  LOST = 'LOST',
  UNRESPONSIVE = 'UNRESPONSIVE',
  DO_NOT_CONTACT = 'DO_NOT_CONTACT'
}

// Lead Source
export enum LeadSource {
  COLD_OUTREACH = 'COLD_OUTREACH',
  EXCEL_IMPORT = 'EXCEL_IMPORT',
  REFERRAL = 'REFERRAL',
  WEBSITE = 'WEBSITE',
  LINKEDIN = 'LINKEDIN',
  INSTAGRAM = 'INSTAGRAM',
  EVENT = 'EVENT',
  EXISTING_CLIENT = 'EXISTING_CLIENT',
  OTHER = 'OTHER'
}

// Service Types 7BLOCKS Offers
export enum ServiceInterest {
  WEBSITE_NEW = 'WEBSITE_NEW',
  WEBSITE_REDESIGN = 'WEBSITE_REDESIGN',
  WEB_APP = 'WEB_APP',
  MOBILE_APP = 'MOBILE_APP',
  AUTOMATION = 'AUTOMATION',
  SAAS = 'SAAS',
  CUSTOM_SOFTWARE = 'CUSTOM_SOFTWARE',
  OTHER = 'OTHER'
}

// Deal Stages
export enum DealStage {
  PROSPECTING = 'PROSPECTING',
  QUALIFICATION = 'QUALIFICATION',
  PROPOSAL = 'PROPOSAL',
  NEGOTIATION = 'NEGOTIATION',
  CLOSED_WON = 'CLOSED_WON',
  CLOSED_LOST = 'CLOSED_LOST'
}

// Activity Types
export enum ActivityType {
  EMAIL_SENT = 'EMAIL_SENT',
  EMAIL_OPENED = 'EMAIL_OPENED',
  EMAIL_REPLIED = 'EMAIL_REPLIED',
  COLD_CALL = 'COLD_CALL',
  WARM_CALL = 'WARM_CALL',
  MEETING_SCHEDULED = 'MEETING_SCHEDULED',
  MEETING_COMPLETED = 'MEETING_COMPLETED',
  FOLLOW_UP = 'FOLLOW_UP',
  NOTE = 'NOTE',
  STATUS_CHANGE = 'STATUS_CHANGE',
  WHATSAPP = 'WHATSAPP',
  DEMO_SENT = 'DEMO_SENT',
  PROPOSAL_SENT = 'PROPOSAL_SENT',
  TASK_COMPLETED = 'TASK_COMPLETED',
  DEAL_CREATED = 'DEAL_CREATED',
  OTHER = 'OTHER'
}

// Activity Outcomes
export enum ActivityOutcome {
  INTERESTED = 'INTERESTED',
  NOT_INTERESTED = 'NOT_INTERESTED',
  NO_ANSWER = 'NO_ANSWER',
  BUSY = 'BUSY',
  CALLBACK_REQUESTED = 'CALLBACK_REQUESTED',
  MEETING_REQUESTED = 'MEETING_REQUESTED',
  DEMO_REQUESTED = 'DEMO_REQUESTED',
  ALREADY_HAS_SOLUTION = 'ALREADY_HAS_SOLUTION',
  WRONG_NUMBER = 'WRONG_NUMBER',
  POSITIVE = 'POSITIVE',
  NEGATIVE = 'NEGATIVE',
  FOLLOW_UP_REQUIRED = 'FOLLOW_UP_REQUIRED',
  DO_NOT_CONTACT = 'DO_NOT_CONTACT',
  OTHER = 'OTHER'
}

// Task Priority & Status
export enum TaskPriority {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  URGENT = 'URGENT'
}

export enum TaskStatus {
  TODO = 'TODO',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED'
}

// Meeting Status
export enum MeetingStatus {
  SCHEDULED = 'SCHEDULED',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  NO_SHOW = 'NO_SHOW'
}

// Notification Types
export enum NotificationType {
  TASK_DUE = 'TASK_DUE',
  FOLLOWUP_DUE = 'FOLLOWUP_DUE',
  DEAL_OVERDUE = 'DEAL_OVERDUE',
  ASSIGNED = 'ASSIGNED',
  EMAIL_REPLY = 'EMAIL_REPLY',
  IMPORT_COMPLETED = 'IMPORT_COMPLETED',
  SYSTEM = 'SYSTEM'
}

// Audit Log Actions
export enum AuditAction {
  USER_CREATED = 'USER_CREATED',
  USER_UPDATED = 'USER_UPDATED',
  CONTACT_CREATED = 'CONTACT_CREATED',
  CONTACT_UPDATED = 'CONTACT_UPDATED',
  CONTACT_DELETED = 'CONTACT_DELETED',
  COMPANY_CREATED = 'COMPANY_CREATED',
  COMPANY_UPDATED = 'COMPANY_UPDATED',
  COMPANY_DELETED = 'COMPANY_DELETED',
  DEAL_CREATED = 'DEAL_CREATED',
  DEAL_UPDATED = 'DEAL_UPDATED',
  DEAL_STAGE_CHANGED = 'DEAL_STAGE_CHANGED',
  DEAL_DELETED = 'DEAL_DELETED',
  TASK_CREATED = 'TASK_CREATED',
  TASK_COMPLETED = 'TASK_COMPLETED',
  TASK_UPDATED = 'TASK_UPDATED',
  TASK_DELETED = 'TASK_DELETED',
  ACTIVITY_LOGGED = 'ACTIVITY_LOGGED',
  IMPORT_COMPLETED = 'IMPORT_COMPLETED',
  EXPORT_CREATED = 'EXPORT_CREATED'
}

// API Response Standard
export interface ApiResponse<T = any> {
  success: boolean;
  data?: T;
  error?: {
    code: string;
    message: string;
    details?: any;
  };
  pagination?: {
    page: number;
    limit: number;
    total: number;
    totalPages: number;
  };
}

// Stage Probability Map
export const STAGE_PROBABILITIES: Record<DealStage, number> = {
  [DealStage.PROSPECTING]: 10,
  [DealStage.QUALIFICATION]: 30,
  [DealStage.PROPOSAL]: 60,
  [DealStage.NEGOTIATION]: 80,
  [DealStage.CLOSED_WON]: 100,
  [DealStage.CLOSED_LOST]: 0
};
